export { default as BusinessComm } from "./BusinessComm";
export { default as CommSkills } from "./CommSkills";
export { default as ConstitutionalLaw } from "./ConstitutionalLaw";
export { default as ContractLaw } from "./ContractLaw";
export { default as CriminalLaw } from "./CriminalLaw";
export { default as French } from "./French";
export { default as GhanaLegalSystems } from "./GhanaLegalSystem";
export { default as IntroEM } from "./IntroEM";
export { default as IntroIT } from "./IntroIT";
export { default as LegalMethods } from "./LegalMethods";
export { default as BusFrench } from "./BusFrench";
export { default as question } from "./question";
// export { default as BusinessComm } from "./BusinessComm";
// export { default as BusMaths } from "./BusMaths";
// export { default as CommSkills } from "./CommSkills";
// export { default as ConstitutionalLaw } from "./ConstitutionalLaw";
// export { default as ContractLaw } from "./ContractLaw";
// export { default as CriminalLaw } from "./CriminalLaw";
// export { default as French } from "./French";
// export { default as GhanaLegalSystems } from "./GhanaLegalSystems";
// export { default as IntroEM } from "./IntroEM";
// export { default as IntroIT } from "./IntroIT";
// export { default as LegalMethods } from "./LegalMethods";
// export { default as BusFrench } from "./BusFrench";
// export { default as BusinessStats } from "./BusinessStats";
